import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import {registerBuilder,validateBrand,suggestCollections,pngData} from '../lib/builder.js';
import {themeFiles,zipFiles} from '../lib/builder-theme.js';
import {newSalt,deriveKey,seal,open} from '../public/vault-crypto.mjs';
const brand={name:'Example',segment:'fashion',language:'en',palette:['#f6f2eb','#242424','#755642'],headline:'Everyday',domain:'example.com'};
const destination={shop:'example.myshopify.com',clientId:'app',clientSecret:'secret'};
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Zl9sAAAAASUVORK5CYII=';
const products=[{id:'gid://shopify/Product/1',title:'Linen dress',tags:[],status:'ACTIVE'},{id:'gid://shopify/Product/2',title:'Cotton shirt',tags:[],status:'DRAFT'}];
const connection=nodes=>({nodes,pageInfo:{hasNextPage:false,endCursor:null}});
async function setup(handler){const app=express();app.use(express.json({limit:'32mb'}));registerBuilder(app,async()=> 'test-token',async(_shop,_token,q,v)=>{if(q.includes('BuilderProducts'))return {products:connection(products)};if(q.includes('BuilderLocations'))return {locations:connection([{id:'gid://shopify/Location/1',name:'Warehouse',isActive:true}])};return handler(q,v);});const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}`;return {base,post:async(path,body={})=>{const r=await fetch(base+'/api/builder/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({destination,...body})});return {status:r.status,data:await r.json()};},close:()=>new Promise(r=>server.close(r))};}
test('vault encrypts secrets, uses random nonces and rejects wrong passwords and tampering',async()=>{const salt=newSalt(),key=await deriveKey('a strong passphrase',salt),data={stores:[{id:'1',name:'Shop',shop:destination.shop,clientId:'id',clientSecret:'very-private-secret'}]};const a=await seal(data,key,salt),b=await seal(data,key,salt);assert.notEqual(a.iv,b.iv);assert.ok(!JSON.stringify(a).includes('very-private-secret'));assert.deepEqual((await open(a,'a strong passphrase')).data,data);await assert.rejects(open(a,'another passphrase'));await assert.rejects(open({...a,body:b.body},'a strong passphrase'));});
test('brand rejects malicious domains, colors and asset types; category suggestions preserve membership',()=>{assert.throws(()=>validateBrand({...brand,domain:'example.com/path'}));assert.throws(()=>validateBrand({...brand,palette:['red','blue','white']}));assert.throws(()=>pngData(Buffer.from('<svg onload="alert(1)">').toString('base64')));assert.equal(pngData(png),png);const groups=suggestCollections(products,'pt');assert.equal(groups[0].title,'Vestidos');assert.deepEqual(groups.flatMap(g=>g.products.map(p=>p.id)),products.map(p=>p.id));});
test('theme package isolates user input in settings and contains functional cart/product templates',()=>{const files=themeFiles({...brand,name:'{% render "bad" %}<script>x</script>'},[{handle:'v2-dresses',title:'Dresses'}],{favicon:png,banner:png});assert.ok(!files['layout/theme.liquid'].includes('<script>x</script>'));assert.match(files['layout/theme.liquid'],/settings.brand \| escape/);assert.match(files['templates/product.liquid'],/form 'product'/);assert.match(files['templates/cart.liquid'],/name="checkout"/);assert.match(files['sections/v2-home.liquid'],/collections\[settings\[key\]\]/);const zip=zipFiles(files);assert.equal(zip.readUInt32LE(0),0x04034b50);assert.equal(zip.readUInt32LE(zip.length-22),0x06054b50);assert.equal(zip.readUInt16LE(zip.length-12),Object.keys(files).length);});
test('analysis is read only, binds credentials, and refuses out-of-snapshot products and unconfirmed stock',async()=>{let writes=0;const s=await setup(()=>{writes++;throw Error('Unexpected call');});try{const p=await s.post('analyze',{brand});assert.equal(p.status,200);assert.equal(p.data.total,2);assert.equal(writes,0);const id=p.data.id;assert.equal((await s.post('collection',{id,key:'dresses',productIds:['gid://shopify/Product/999'],confirmShop:destination.shop})).status,400);assert.equal((await s.post('collection',{id,destination:{...destination,clientSecret:'other'}})).status,400);assert.equal((await s.post('stock',{id,productId:products[0].id,quantity:10,locationId:'gid://shopify/Location/1'})).status,400);assert.equal(writes,0);}finally{await s.close();}});
test('existing collections are skipped with no mutations',async()=>{const s=await setup((q)=>{assert.ok(q.startsWith('query BuilderCollection'));return {collections:{nodes:[{id:'gid://shopify/Collection/3',handle:'v2-dresses',title:'Existing'}]}};});try{const id=(await s.post('analyze',{brand})).data.id;const r=await s.post('collection',{id,key:'dresses',productIds:[products[0].id],confirmShop:destination.shop});assert.equal(r.status,200);assert.equal(r.data.skipped,true);assert.equal(r.data.title,'Existing');}finally{await s.close();}});
test('collection retry resumes after publication failure without duplicate creation or membership',async()=>{let creates=0,adds=0,publishes=0;const members=[];const s=await setup((q,v)=>{if(q.startsWith('query BuilderCollection('))return {collections:{nodes:[]}};if(q.includes('BuilderCollectionCreate')){creates++;return {collectionCreate:{collection:{id:'gid://shopify/Collection/3',title:v.input.title,handle:v.input.handle},userErrors:[]}};}if(q.includes('BuilderMembers'))return {collection:{products:connection(members)}};if(q.includes('BuilderCollectionAdd')){adds++;members.push(...v.products.map(id=>({id})));return {collectionAddProducts:{collection:{id:v.id},userErrors:[]}};}if(q.includes('BuilderPublications'))return {publications:connection([{id:'gid://shopify/Publication/1',name:'Online Store'}])};if(q.includes('BuilderPublishCollection')){publishes++;return {publishablePublish:{userErrors:publishes===1?[{message:'Temporary failure'}]:[]}};}throw Error(q);});try{const id=(await s.post('analyze',{brand})).data.id;const body={id,key:'dresses',title:'Dresses',productIds:[products[0].id],confirmShop:destination.shop};assert.equal((await s.post('collection',body)).status,400);assert.equal((await s.post('collection',body)).data.complete,true);assert.equal((await s.post('collection',body)).data.complete,true);assert.equal(creates,1);assert.equal(adds,1);assert.equal(publishes,2);}finally{await s.close();}});
test('theme stays unpublished, repeated preparation reuses draft, and publish checks readiness',async()=>{let creates=0,publishes=0,processing=true,source;const s=await setup((q,v)=>{if(q.includes('mutation BuilderTheme(')){creates++;source=v.source;assert.match(q,/role:UNPUBLISHED/);return {themeCreate:{theme:{id:'gid://shopify/OnlineStoreTheme/1',role:'UNPUBLISHED',processing:true},userErrors:[]}};}if(q.includes('BuilderThemeReady'))return {theme:{id:'gid://shopify/OnlineStoreTheme/1',processing,processingFailed:false,role:'UNPUBLISHED'}};if(q.includes('BuilderThemePublish')){publishes++;return {themePublish:{theme:{id:v.id,role:'MAIN'},userErrors:[]}};}throw Error(q);});try{const id=(await s.post('analyze',{brand})).data.id,body={id,brand,keys:[],assets:{favicon:png,banner:png},confirmShop:destination.shop};assert.equal((await s.post('theme',body)).status,200);assert.equal((await s.post('theme',body)).status,200);assert.equal(creates,1);assert.equal(publishes,0);const packageResponse=await fetch(s.base+new URL(source).pathname);assert.equal(packageResponse.status,200);assert.equal(Buffer.from(await packageResponse.arrayBuffer()).readUInt32LE(0),0x04034b50);const publish={id,themeId:'gid://shopify/OnlineStoreTheme/1',confirmShop:destination.shop};assert.equal((await s.post('publish',publish)).status,400);assert.equal(publishes,0);processing=false;assert.equal((await s.post('publish',publish)).data.ok,true);assert.equal(publishes,1);assert.equal((await s.post('publish',{...publish,themeId:'gid://shopify/OnlineStoreTheme/99'})).status,400);}finally{await s.close();}});
