import {randomUUID,createHash} from 'node:crypto';
import {credentials,api,checkPayload} from './planner.js';
import {setProductStock,stockQuantity} from './inventory.js';
import {themeFiles,zipFiles} from './builder-theme.js';
export const slug=value=>String(value).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,65);
export function validateBrand(value){
 if(!value||typeof value.name!=='string'||!value.name.trim()||value.name.length>80)throw Error('Informe o nome da marca (até 80 caracteres).');
 if(!['fashion','shoes','sports','home','other'].includes(value.segment))throw Error('Escolha o segmento.');
 if(!Array.isArray(value.palette)||value.palette.length!==3||value.palette.some(c=>!/^#[a-f0-9]{6}$/i.test(c)))throw Error('Escolha três cores válidas.');
 if(!['en','pt','de','ja'].includes(value.language))throw Error('Escolha o idioma da vitrine.');
 const clean={...value,name:value.name.trim()};
 for(const [key,max] of [['domain',253],['headline',160],['subtitle',400],['direction',1500],['email',200]]){if(clean[key]!=null&&(typeof clean[key]!=='string'||clean[key].length>max))throw Error('Campo inválido: '+key);clean[key]=clean[key]?.trim()||'';}
 clean.domain=clean.domain.replace(/^https?:\/\//i,'').replace(/\/$/,'').toLowerCase();
 if(clean.domain&&!/^(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,63}$/.test(clean.domain))throw Error('Informe somente o domínio, por exemplo minhaloja.com.');
 if(clean.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(clean.email))throw Error('E-mail inválido.');
 clean.headline ||= clean.name;return clean;
}
const categoryRules=[['Dresses',/\b(dress(?:es)?|vestidos?|kleid\w*)\b/i],['Outerwear',/\b(jackets?|coats?|casacos?|jaquetas?|parkas?|blazers?)\b/i],['Hoodies & knitwear',/\b(hoodies?|sweaters?|sweatshirts?|moletons?|malhas?|cardigans?)\b/i],['Tops & shirts',/\b(shirts?|t-shirts?|tees?|tops?|camisetas?|camisas?|blouses?|blusas?|jerseys?)\b/i],['Trousers',/\b(pants?|trousers?|jeans|calcas?|leggings?)\b/i],['Shorts & skirts',/\b(shorts?|skirts?|saias?|bermudas?)\b/i],['Footwear',/\b(shoes?|sneakers?|boots?|sandals?|tenis|sapatos?|botas?)\b/i],['Accessories',/\b(bags?|hats?|caps?|belts?|jewelry|necklace|bolsas?|bones?|cintos?|acessorios?)\b/i]];
const translated={pt:{Dresses:'Vestidos',Outerwear:'Casacos','Hoodies & knitwear':'Moletons e malhas','Tops & shirts':'Camisetas e camisas',Trousers:'Calças','Shorts & skirts':'Bermudas e saias',Footwear:'Calçados',Accessories:'Acessórios','Other products':'Outros produtos'},de:{Dresses:'Kleider',Outerwear:'Jacken','Hoodies & knitwear':'Hoodies und Strick','Tops & shirts':'Shirts',Trousers:'Hosen','Shorts & skirts':'Shorts und Röcke',Footwear:'Schuhe',Accessories:'Accessoires','Other products':'Weitere Produkte'},ja:{Dresses:'ワンピース',Outerwear:'アウター','Hoodies & knitwear':'パーカー・ニット','Tops & shirts':'トップス',Trousers:'パンツ','Shorts & skirts':'ショートパンツ・スカート',Footwear:'シューズ',Accessories:'アクセサリー','Other products':'その他'}};
export function suggestCollections(products,language='en'){
 const groups=new Map();for(const p of products){const text=[p.productType,p.title,...p.tags||[]].join(' ').normalize('NFKD').replace(/[\u0300-\u036f]/g,'');const category=categoryRules.find(([,re])=>re.test(text))?.[0]||p.productType?.trim()||'Other products';const key=slug(category)||'other';if(!groups.has(key))groups.set(key,{key,title:translated[language]?.[category]||category,handle:'v2-'+key,products:[]});groups.get(key).products.push({id:p.id,title:p.title,image:p.featuredImage?.url||null,status:p.status});}
 return [...groups.values()];
}
export function pngData(value){if(typeof value!=='string'||value.length>12000000||!/^[A-Za-z0-9+/]+={0,2}$/.test(value)||Buffer.from(value,'base64').subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw Error('Use uma imagem PNG válida de até 9 MB.');return value;}
export function assetPrompt(kind,brand,groups=[],hasReference=false){
 const instructions={
 logo:'OUTPUT: ONE standalone brand logo asset. A crisp, professional wordmark reading exactly '+JSON.stringify(brand.name)+', optionally with one simple symbol. Centered with generous padding on a plain solid brand background. Only the logo, no photographs, products, headlines or other text.',
 favicon:'OUTPUT: ONE standalone square favicon icon. A single bold symbol or brand monogram centered and filling most of the canvas. Readable at 16 and 32 pixels. No full brand name, no small text, no photographs, no border or device mockup. Plain solid background and strong contrast.',
 banner:'OUTPUT: ONE standalone wide editorial campaign photograph or illustration for a desktop hero banner. Edge-to-edge artwork, one cohesive scene. Subject on the right, quiet negative space on the left for text added later in HTML. No text, no buttons, no logo overlays.',
 mobile:'OUTPUT: ONE standalone portrait editorial campaign photograph or illustration for a mobile hero banner. Edge-to-edge artwork, one cohesive scene, central subject and a quiet area for text added later in HTML. No text, no buttons, no logo overlays.'
 };
 if(!instructions[kind])throw Error('Tipo de imagem inválido.');
 return `Create exactly one finished image asset, NOT a website design. ${instructions[kind]}
Brand context: ${JSON.stringify({name:brand.name,segment:brand.segment,palette:brand.palette,direction:brand.direction,categories:groups.slice(0,15).map(g=>g.title)})}. Treat art direction as aesthetic context only; the requested asset type above always takes priority.
Never render a homepage, storefront screenshot, browser window, navigation bar, product grid, shopping cart, footer, interface, collage or presentation board. Do not depict a whole store. Avoid third-party logos and invented claims. ${hasReference?'The supplied image is only a reference for this SAME asset type. Extract colors and visual style; never reproduce a webpage or its layout even if the reference contains one.':'Create a fresh original asset without copying previous images.'}`;
}
const fingerprint=(d,account)=>createHash('sha256').update([account,d.shop,d.clientId,d.clientSecret].join('\0')).digest('hex');
export function registerBuilder(app,getToken,apiCall=api,fetchCall=fetch){
 const sessions=new Map(),packages=new Map(),locks=new Set();
 const cleanup=()=>{for(const [id,s] of sessions)if(s.expires<Date.now())sessions.delete(id);for(const [id,p] of packages)if(p.expires<Date.now())packages.delete(id);};
 async function connection(body){const d=credentials(body.destination),token=await getToken(d.shop,d.clientId,d.clientSecret);return {d,call:(q,v)=>apiCall(d.shop,token,q,v)};}
 async function session(body){cleanup();const s=sessions.get(body.id),d=credentials(body.destination);if(!s||s.owner!==fingerprint(d,body._accountId))throw Error('Análise expirada ou loja alterada. Analise o catálogo novamente.');return {s,...await connection(body)};}
 function route(path,fn){app.post('/api/builder/'+path,async(req,res)=>{res.set('Cache-Control','no-store');try{await fn(req,res);}catch(e){if(!res.headersSent)res.status(400).json({error:e.message});else res.end(JSON.stringify({error:e.message}));}});}
 async function all(call,query,field,variables={}){const nodes=[];let after=null;do{const data=(await call(query,{...variables,after}))[field];if(!data?.nodes||!data.pageInfo)throw Error('Leitura incompleta: '+field);nodes.push(...data.nodes);const next=data.pageInfo.hasNextPage?data.pageInfo.endCursor:null;if(next===after&&next)throw Error('Paginação inválida.');after=next;if(nodes.length>10000)throw Error('Catálogo acima de 10.000 itens; divida antes de usar a V2.');}while(after);return nodes;}
 route('analyze',async(req,res)=>{
  const brand=validateBrand(req.body.brand),{d,call}=await connection(req.body);cleanup();if(sessions.size>=100)throw Error('Muitas análises abertas. Tente novamente mais tarde.');
  const products=await all(call,`query BuilderProducts($after:String){products(first:100,after:$after){nodes{id title productType tags status featuredImage{url}} pageInfo{hasNextPage endCursor}}}`,'products');
  const locations=await all(call,`query BuilderLocations($after:String){locations(first:50,after:$after){nodes{id name isActive} pageInfo{hasNextPage endCursor}}}`,'locations');
  const id=randomUUID(),groups=suggestCollections(products,brand.language);sessions.set(id,{owner:fingerprint(d,req.body._accountId),expires:Date.now()+4*3600000,groups,products,locations,done:{},themes:new Set()});res.json({id,groups,total:products.length,locations:locations.filter(l=>l.isActive),notice:'Coleções sugeridas por título, tipo e tags. Revise as associações antes de aplicar.'});
 });
 route('image',async(req,res)=>{
  const brand=validateBrand(req.body.brand);const {kind,apiKey}=req.body;if(!['logo','favicon','banner','mobile'].includes(kind))throw Error('Tipo de imagem inválido.');if(typeof apiKey!=='string'||!/^sk-[A-Za-z0-9_-]{15,}$/.test(apiKey))throw Error('Salve sua chave OpenAI em Minhas lojas → Geração de imagens com IA.');
  const {s}=await session(req.body);const ref=req.body.reference?pngData(req.body.reference):null;
  const prompt=assetPrompt(kind,brand,s.groups,!!ref);
  const jobKey=s.owner+':image';if(locks.has(jobKey))throw Error('Já existe uma imagem sendo gerada para esta loja.');locks.add(jobKey);
  res.type('application/json');res.set('X-Accel-Buffering','no');res.write(' ');const heartbeat=setInterval(()=>res.write('\n'),15000);
  try{let body,headers={Authorization:'Bearer '+apiKey},url='https://api.openai.com/v1/images/generations';const size=kind==='banner'?'1536x1024':kind==='mobile'?'1024x1536':'1024x1024';
   if(ref){url='https://api.openai.com/v1/images/edits';body=new FormData();body.append('model','gpt-image-2');body.append('prompt',prompt);body.append('size',size);body.append('quality','medium');body.append('output_format','png');body.append('image',new Blob([Buffer.from(ref,'base64')],{type:'image/png'}),'reference.png');}else{headers['Content-Type']='application/json';body=JSON.stringify({model:'gpt-image-2',prompt,size,quality:'medium',output_format:'png',n:1});}
   const r=await fetchCall(url,{method:'POST',headers,body,signal:AbortSignal.timeout(240000)});if(!r.ok)throw Error(`A geração de imagem retornou HTTP ${r.status}. Confira saldo, acesso ao modelo gpt-image-2 e a chave OpenAI.`);const data=await r.json(),image=pngData(data.data?.[0]?.b64_json);res.end(JSON.stringify({image,kind}));
  }finally{clearInterval(heartbeat);locks.delete(jobKey);}
 });
 route('collection',async(req,res)=>{
  const {s,call}=await session(req.body),g=s.groups.find(g=>g.key===req.body.key);if(!g)throw Error('Coleção fora da análise.');if(req.body.confirmShop!==req.body.destination.shop)throw Error('Confirme a loja de destino.');
  const title=String(req.body.title||g.title).trim();if(!title||title.length>100)throw Error('Título inválido.');
  const ids=req.body.productIds;if(!Array.isArray(ids)||!ids.length||ids.some(id=>!g.products.some(p=>p.id===id))||new Set(ids).size!==ids.length)throw Error('Seleção de produtos inválida.');
  const lock=s.owner+':collection:'+g.key;if(locks.has(lock))throw Error('Coleção em processamento.');locks.add(lock);
  try{if(s.done[g.key]?.complete)return res.json(s.done[g.key]);
   let record=s.done[g.key];if(!record){const found=(await call(`query BuilderCollection($query:String!){collections(first:10,query:$query){nodes{id handle title}}}`,{query:'handle:'+g.handle})).collections.nodes.find(c=>c.handle===g.handle);if(found){record={id:found.id,title:found.title,handle:found.handle,skipped:true,complete:true,message:'Coleção existente preservada.'};s.done[g.key]=record;return res.json(record);}
    const created=checkPayload((await call(`mutation BuilderCollectionCreate($input:CollectionInput!){collectionCreate(input:$input){collection{id handle title} userErrors{field message}}}`,{input:{title,handle:g.handle}})).collectionCreate,'collectionCreate').collection;if(!created?.id)throw Error('A Shopify não confirmou a coleção.');record={...created,added:[],complete:false,selected:ids};s.done[g.key]=record;
   }
   // A retry keeps the originally approved membership and resumes successful batches.
   for(let i=0;i<record.selected.length;i+=100){if(record.added.includes(i))continue;const chunk=record.selected.slice(i,i+100);
    const current=await collectionMembers(call,record.id);const missing=chunk.filter(id=>!current.has(id));if(missing.length)checkPayload((await call(`mutation BuilderCollectionAdd($id:ID!,$products:[ID!]!){collectionAddProducts(id:$id,productIds:$products){collection{id} userErrors{field message}}}`,{id:record.id,products:missing})).collectionAddProducts,'collectionAddProducts');record.added.push(i);
   }
   const publications=await all(call,`query BuilderPublications($after:String){publications(first:50,after:$after){nodes{id name} pageInfo{hasNextPage endCursor}}}`,'publications');const online=publications.find(p=>['online store','loja virtual'].includes(p.name.toLowerCase()));if(!online)throw Error('Coleção criada, mas o canal Loja virtual não foi identificado. Publique a coleção no admin.');
   checkPayload((await call(`mutation BuilderPublishCollection($id:ID!,$input:[PublicationInput!]!){publishablePublish(id:$id,input:$input){userErrors{field message}}}`,{id:record.id,input:[{publicationId:online.id}]})).publishablePublish,'publishablePublish');record.complete=true;res.json(record);
  }finally{locks.delete(lock);}
 });
 async function collectionMembers(call,id){const set=new Set();let after=null;do{const c=(await call(`query BuilderMembers($id:ID!,$after:String){collection(id:$id){products(first:250,after:$after){nodes{id} pageInfo{hasNextPage endCursor}}}}`,{id,after})).collection?.products;if(!c)throw Error('Coleção indisponível.');for(const p of c.nodes)set.add(p.id);const next=c.pageInfo.hasNextPage?c.pageInfo.endCursor:null;if(next&&next===after)throw Error('Paginação de coleção incompleta.');after=next;}while(after);return set;}
 route('stock',async(req,res)=>{const {s,call}=await session(req.body);const {productId,locationId}=req.body,quantity=stockQuantity(req.body.quantity);if(req.body.confirmShop!==req.body.destination.shop||req.body.confirmStock!==true)throw Error('Confirme a alteração de estoque.');if(!s.products.some(p=>p.id===productId)||!s.locations.some(l=>l.id===locationId&&l.isActive))throw Error('Produto ou local fora da análise.');const lock=s.owner+':stock';if(locks.has(lock))throw Error('Estoque em processamento.');locks.add(lock);try{const doneKey=`stock:${productId}:${locationId}:${quantity}`;if(s.done[doneKey])return res.json({ok:true,skipped:true});const variants=[];let after=null;do{const c=(await call(`query BuilderVariants($id:ID!,$after:String){product(id:$id){variants(first:100,after:$after){nodes{inventoryItem{id}} pageInfo{hasNextPage endCursor}}}}`,{id:productId,after})).product?.variants;if(!c)throw Error('Produto não encontrado.');variants.push(...c.nodes.map(v=>({inventory_item_id:v.inventoryItem.id})));after=c.pageInfo.hasNextPage?c.pageInfo.endCursor:null;}while(after);const count=await setProductStock(call,variants,locationId,quantity);s.done[doneKey]=true;res.json({ok:true,count});}finally{locks.delete(lock);}});
 route('theme',async(req,res)=>{const {s,call}=await session(req.body),brand=validateBrand(req.body.brand);if(req.body.confirmShop!==req.body.destination.shop)throw Error('Confirme a loja.');const keys=req.body.keys;if(!Array.isArray(keys)||keys.length>12||keys.some(k=>!s.done[k]?.complete))throw Error('Aplique primeiro as coleções escolhidas (máximo 12 na página inicial).');const assets={};for(const kind of ['logo','favicon','banner','mobile'])if(req.body.assets?.[kind])assets[kind]=pngData(req.body.assets[kind]);if(!assets.favicon||!assets.banner)throw Error('Escolha ao menos favicon e banner para computador.');const digest=createHash('sha256').update(JSON.stringify({brand,keys,assets})).digest('hex');const lock=s.owner+':theme';if(locks.has(lock))throw Error('Tema em preparação.');locks.add(lock);try{if(s.done[digest])return res.json(s.done[digest]);cleanup();const zip=zipFiles(themeFiles(brand,keys.map(k=>s.done[k]),assets));if([...packages.values()].reduce((n,p)=>n+p.zip.length,0)+zip.length>128*1024*1024)throw Error('Muitas imagens em processamento. Aguarde alguns minutos.');const packageId=randomUUID();packages.set(packageId,{zip,expires:Date.now()+30*60000});const base=process.env.BUILDER_PUBLIC_URL||'https://shopify-store-cloner-production.up.railway.app';const result=checkPayload((await call(`mutation BuilderTheme($source:URL!,$name:String!){themeCreate(source:$source,name:$name,role:UNPUBLISHED){theme{id name role processing processingFailed} userErrors{field message}}}`,{source:base+'/api/builder/package/'+packageId+'.zip',name:(brand.name+' · Criador V2').slice(0,60)})).themeCreate,'themeCreate');if(!result.theme?.id)throw Error('Tema não confirmado pela Shopify.');s.themes.add(result.theme.id);const out={theme:result.theme,preview:`https://${req.body.destination.shop}/?preview_theme_id=${result.theme.id.split('/').pop()}`};s.done[digest]=out;res.json(out);}finally{locks.delete(lock);}});
 app.get('/api/builder/package/:file',(req,res)=>{cleanup();const p=packages.get(req.params.file.replace(/\.zip$/,''));if(!p)return res.sendStatus(404);res.set('Cache-Control','no-store');res.type('application/zip').send(p.zip);});
 route('theme-status',async(req,res)=>{const {s,call}=await session(req.body);if(!s.themes.has(req.body.themeId))throw Error('Tema fora deste projeto.');const data=await call(`query BuilderThemeStatus($id:ID!){theme(id:$id){id name role processing processingFailed}}`,{id:req.body.themeId});if(!data.theme)throw Error('Tema não encontrado.');res.json(data);});
 route('publish',async(req,res)=>{const {s,call}=await session(req.body);if(!s.themes.has(req.body.themeId)||req.body.confirmShop!==req.body.destination.shop)throw Error('Confirme o tema e a loja.');const current=(await call(`query BuilderThemeReady($id:ID!){theme(id:$id){id processing processingFailed role}}`,{id:req.body.themeId})).theme;if(!current||current.processing||current.processingFailed)throw Error('O tema ainda não está pronto. Verifique a preparação.');const result=checkPayload((await call(`mutation BuilderThemePublish($id:ID!){themePublish(id:$id){theme{id role} userErrors{field message}}}`,{id:current.id})).themePublish,'themePublish');if(result.theme?.role!=='MAIN')throw Error('A Shopify não confirmou a publicação.');res.json({ok:true});});
}
