import {randomUUID} from 'node:crypto';
import {credentials,api,checkPayload} from './planner.js';
export const POLICY_TITLES={SHIPPING_POLICY:'Política de frete',REFUND_POLICY:'Trocas e devoluções',PRIVACY_POLICY:'Privacidade',TERMS_OF_SERVICE:'Termos de serviço',TERMS_OF_SALE:'Termos de venda',CONTACT_INFORMATION:'Informações de contato',LEGAL_NOTICE:'Aviso legal'};
const required={storeName:'Nome da loja',company:'Razão social / vendedor',address:'Endereço comercial completo',email:'E-mail de suporte',phone:'Telefone',returnAddress:'Endereço de devolução',processing:'Prazo de processamento',delivery:'Prazo de transporte',shippingFees:'Valores de frete',payments:'Meios e momento de pagamento',retention:'Prazo / critério de retenção dos dados',providers:'Prestadores e países de tratamento dos dados',hours:'Horário de atendimento'};
export function policyDefaults(region='world'){
 const jp=region==='japan';
 return {region,language:jp?'ja':'en',returnDays:30,returnCost:'customer',duties:'customer',marketing:true,
 processing:jp?'1～3営業日':'1–3 business days',delivery:jp?'発送後5～12営業日':'5–12 business days after dispatch',
 shippingFees:jp?'配送先と配送方法に応じてチェックアウトで表示':'Displayed at checkout according to destination and delivery method',
 payments:jp?'チェックアウトに表示される決済方法。注文時に決済':'Payment methods shown at checkout; payment is due when ordering',
 retention:jp?'注文処理とサポートに必要な期間、および適用される会計・法的保存義務を満たす期間':'For the duration needed to fulfil orders and support requests, plus applicable statutory accounting and legal retention periods',
 providers:jp?'Shopify（ストア運営）、選択された決済事業者と配送事業者。処理国と移転条件は各提供者の契約・通知に従います。詳細は当店へお問い合わせください。':'Shopify (store platform), selected payment providers and delivery providers. Processing locations and transfer arrangements depend on each provider’s agreements and notices; contact us for details.',
 hours:jp?'メールでお問い合わせください。通常2営業日以内に返信します。':'Contact us by email; we aim to respond within 2 business days'};
}
export function validatePolicyInput(input){
 if(!input||!['europe','japan','world'].includes(input.region))throw Error('Escolha Europa, Japão ou mundo todo.');
 if(input.language&&!['en','ja'].includes(input.language))throw Error('Escolha inglês ou japonês.');
 const v={...policyDefaults(input.region),...input};
 v.returnAddress=v.returnAddress?.trim()||v.address;
 for(const [key,label] of Object.entries(required)){if(typeof v[key]!=='string'||!v[key].trim()||v[key].length>2000)throw Error('Preencha: '+label);v[key]=v[key].trim();}
 if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.email))throw Error('E-mail inválido.');
 if(!Number.isInteger(Number(v.returnDays))||Number(v.returnDays)<1||Number(v.returnDays)>365)throw Error('Prazo de devolução deve ser entre 1 e 365 dias.');
 v.returnDays=Number(v.returnDays);
 if(v.region!=='japan'&&v.returnDays<14)throw Error('Para Europa/mundo, use pelo menos 14 dias; direitos obrigatórios são preservados.');
 if(!['customer','store'].includes(v.returnCost)||!['included','customer'].includes(v.duties)||typeof v.marketing!=='boolean')throw Error('Revise devolução, impostos e uso de marketing.');
 if(v.region!=='europe'&&(!v.manager?.trim()||v.manager.length>200))throw Error('Informe o responsável pela venda para o Japão (também incluído em mundo todo).');
 for(const k of ['manager','registration'])if(v[k]!=null&&(typeof v[k]!=='string'||v[k].length>1000))throw Error('Dados da empresa inválidos.');
 return v;
}
export function generatePolicies(input){
 const v=validatePolicyInput(input),jp=v.language==='ja',eu=v.region!=='japan',japan=v.region!=='europe';
 const region=jp?{europe:'ヨーロッパ',japan:'日本',world:'世界各国'}[v.region]:{europe:'Europe',japan:'Japan',world:'Worldwide'}[v.region];
 const contact=`${v.storeName}\n${v.company}\n${v.address}\n${v.email}\n${v.phone}\n${v.hours}`;
 const identity=jp?`販売業者：${v.company}\n店舗名：${v.storeName}\n所在地：${v.address}\nメール：${v.email}\n電話番号：${v.phone}\n受付時間：${v.hours}`:`Seller: ${v.company}\nStore: ${v.storeName}\nBusiness address: ${v.address}\nSupport: ${v.email}\nTelephone: ${v.phone}\nSupport hours: ${v.hours}`;
 const returnCost=jp?(v.returnCost==='store'?'お客様都合の返品送料は当店が負担します。':'お客様都合の返品送料はお客様のご負担となります。'):(v.returnCost==='store'?'We pay return shipping for change-of-mind returns.':'You pay return shipping for change-of-mind returns.');
 const duty=jp?(v.duties==='included'?'表示された合計金額に輸入関税・税金を含みます。':'輸入関税・税金が別途発生する場合はお客様の負担となります。法令上販売者が徴収・負担すべき税金は除きます。'):(v.duties==='included'?'Import duties and taxes are included in the displayed total.':'Import duties and taxes may be payable by the recipient, except amounts the seller must collect or pay under applicable law.');
 const euReturn=jp?'EUの消費者：通常、商品受領後14日以内は理由を示さず撤回を通知できます。通知から14日以内に返送してください。法定の例外を除き、未使用という条件だけで法定撤回権を制限しません。必要な確認を超える取扱いによる価値の減少は控除対象となる場合があります。撤回通知後14日以内に商品代金と標準配送費を返金しますが、商品または返送証明の受領まで返金を保留できる場合があります。追加の速達料金は対象外です。':'EU consumers: you generally have 14 days from receiving goods to notify us of withdrawal without giving a reason, and 14 further days to send them back. Statutory exceptions apply. The unused condition below does not restrict statutory inspection rights; deductions may apply for handling beyond what is necessary to inspect the goods. We refund the purchase and standard outbound delivery cost within 14 days of withdrawal notification, but may withhold reimbursement until receiving the goods or proof of return. Express delivery upgrades are not refundable under this rule.';
 const guarantee=jp?'不良品・誤配送・契約に適合しない商品についてはご連絡ください。必要な是正および返品費用は当店が負担します。任意の返品期間は法定の保証や救済を制限しません。':'Contact us about damaged, incorrect or non-conforming goods. We bear the costs of the required remedy and return. Our voluntary return period does not limit statutory guarantees or remedies.';
 const euGuarantee=jp?'EUでは原則として引渡しから最低2年間の法定保証があり、国内法による追加保護が優先します。':'EU consumers benefit from a minimum two-year legal guarantee for goods, subject to applicable national rules and any longer protection.';
 const refund=jp?`返品・交換・返金\n\n${identity}\n\n商品受領後${v.returnDays}日以内に、注文番号を添えて${v.email}へ返品または交換をご連絡ください。任意の返品では、商品は未使用で、可能な場合は付属品・タグを含めて返送してください。交換は在庫状況により対応し、用意できない場合は返品・返金をご案内します。\n\n返品先：${v.returnAddress}\n${returnCost}\n${guarantee}\n\n返品確認後14日以内に原則として元の支払方法で返金します。より早い法定期限がある場合はそれを優先します。\n\n${eu?euReturn+'\n\n'+euGuarantee:''}\n\n${japan?'日本の通信販売には一般的なクーリング・オフ制度はありません。当店の返品特約は上記のとおりです。商品ページと最終確認画面でも返品条件をご確認ください。法定の権利を排除するものではありません。':''}`:`Returns, exchanges and refunds\n\n${identity}\n\nContact ${v.email} with your order number within ${v.returnDays} days of receiving your item to request a return or exchange. For voluntary returns, goods should be unused and include accessories and tags where available. Exchanges depend on stock; if a replacement is unavailable, we will explain the return and refund options.\n\nReturn address: ${v.returnAddress}\n${returnCost}\n${guarantee}\n\nApproved refunds are issued to the original payment method within 14 days of receiving the return, unless applicable law requires earlier payment.\n\n${eu?euReturn+'\n\n'+euGuarantee:''}\n\n${japan?'For Japanese mail-order purchases, there is no general cooling-off system. Our contractual return conditions are stated above and must also be shown with the offer and final order confirmation. Mandatory remedies remain unaffected.':''}`;
 const shipping=jp?`配送ポリシー\n\n配送対象：${region}。実際に配送可能な国・住所はチェックアウトで確認できます。\n発送準備期間：${v.processing}\n発送後のお届け目安：${v.delivery}\n送料：${v.shippingFees}\n${duty}\n\n準備期間と配送期間は別です。商品ごとに別の予定日が表示される場合は、その表示をご確認ください。配送遅延・紛失・破損がある場合は${v.email}までご連絡ください。配送業者への引渡しだけで当店の法的責任が終了するものではありません。ご注文後の住所変更は発送前にご相談ください。\n\n${contact}`:`Shipping policy\n\nDelivery area: ${region}. Eligible destinations and addresses are confirmed at checkout.\nOrder processing: ${v.processing}\nEstimated transit after dispatch: ${v.delivery}\nShipping charges: ${v.shippingFees}\n${duty}\n\nProcessing and transit are separate periods. Check any product-specific delivery date before ordering. For delays, loss or damage, contact ${v.email}; handing a parcel to a carrier does not remove our legal obligations to you. Request address changes before dispatch.\n\n${contact}`;
 const sales=jp?`販売条件\n\n${identity}\n\n販売価格：各商品ページに表示します。送料および追加費用：${v.shippingFees}。お支払い総額は注文確定前に表示します。${duty}\n支払方法・時期：${v.payments}\n発送準備：${v.processing}\n配送目安：${v.delivery}\n\n購入可能な配送先は${region}のうちチェックアウトに表示される場所です。注文確定前に商品、数量、金額、配送先を確認してください。確認メールをご確認いただき、誤りがある場合は速やかにご連絡ください。欠品で履行できない場合はお知らせし、未提供分を返金します。発送前のキャンセルはサポートへご連絡ください。発送後は返品条件が適用されます。返品・交換は受領後${v.returnDays}日以内にご連絡ください。返品ポリシーをご覧ください。法定の消費者保護はこれらの条件より優先します。`:`Terms of sale\n\n${identity}\n\nProduct prices appear on product pages. Shipping and additional charges: ${v.shippingFees}. The order total is shown before you confirm payment. ${duty}\nPayment methods and timing: ${v.payments}\nProcessing: ${v.processing}\nTransit estimate: ${v.delivery}\n\nWe sell to eligible checkout destinations within ${region}. Review the products, quantities, total and delivery address before ordering. Check the confirmation email and contact us promptly if anything is incorrect. If stock prevents fulfilment, we will notify you and refund the unfulfilled portion. Contact support to request cancellation before dispatch; after dispatch, the returns policy applies. Request returns or exchanges within ${v.returnDays} days of receipt as explained in that policy. Mandatory consumer rights take priority over these terms.`;
 const marketing=jp?(v.marketing?'同意等の適切な法的根拠に基づきマーケティングとアクセス解析にも利用します。不要なCookieは必要な同意を得た後に使用し、配信停止・同意撤回の手段を提供します。':'お客様のデータを広告配信・任意のアクセス解析には使用しません。'):(v.marketing?'We also use data for marketing and analytics on the appropriate legal basis. Where consent is required, optional cookies are used only after consent; you can withdraw consent or unsubscribe.':'We do not use customer data for advertising or optional analytics.');
 const privacy=jp?`プライバシーポリシー\n\n個人情報の管理者：${v.company}\n住所：${v.address}\n連絡先：${v.email}\n\n取得する情報：氏名、連絡先、配送先、注文・決済状況、お問い合わせ内容、端末・通信に関する情報。決済情報は決済事業者がその役割に応じて処理します。利用目的：注文受付、決済、配送、サポート、不正防止、安全性の確保、会計・法令上の義務への対応。契約の履行、法的義務、必要かつ適切な正当な利益、または同意に基づいて処理します。${marketing}\n\nサービス提供者・処理国：${v.providers}\nShopifyを含むサービス提供者は、それぞれの役割と契約に従って情報を処理します。国外への移転は適用法上必要な保護措置または同意に従います。移転先・保護措置の詳細は上記窓口でご案内します。\n\n保存期間・基準：${v.retention}\n\n適用法に従い、開示、訂正、削除、利用停止、同意撤回等をご請求いただけます。本人確認に必要な情報をお願いする場合があります。EUで適用される場合は処理の制限、異議申立て、データポータビリティの権利もあります。所管の監督機関への申立ても可能です。日本では個人情報保護委員会が監督機関です。必要な情報が提供されない場合、注文を処理できないことがあります。方針の更新時はこのページを改訂し、法令上必要な通知を行います。`:`Privacy policy\n\nData controller: ${v.company}\nAddress: ${v.address}\nPrivacy contact: ${v.email}\n\nWe process names, contact and shipping details, orders, payment status, support messages, and device/connection information. Payment providers process payment details according to their role. We use information to fulfil orders, process payments, deliver goods, provide support, prevent fraud, maintain security, and meet accounting and legal obligations. Depending on the purpose, the legal basis is contract performance, legal obligation, necessary and proportionate legitimate interests, or consent. ${marketing}\n\nService providers and processing countries: ${v.providers}\nShopify and other providers process information according to their roles and agreements. International transfers are subject to safeguards or consent required by applicable law. Contact us for details of destinations and safeguards.\n\nRetention periods and criteria: ${v.retention}\n\nSubject to applicable law, you may request access, correction, deletion, restriction, portability, or object to processing and withdraw consent. We may need proportionate identity verification. You may complain to your local data protection authority; in Japan this is the Personal Information Protection Commission. Required order details are necessary to fulfil your purchase. We update this notice when practices change and provide any legally required notifications.`;
 const terms=jp?`利用規約\n\n${identity}\n\n本サイトは商品の閲覧、購入、サポートのためにご利用いただけます。正確な注文情報を提供し、不正利用、システムへの攻撃、第三者の権利侵害を行わないでください。商品画像・説明・価格は購入前にご確認ください。表示の誤りが注文に影響する場合は、適用法に従いご連絡して対応します。\n\n購入条件は販売条件、配送は配送ポリシー、返品は返品ポリシー、個人情報はプライバシーポリシーに記載します。本規約は強行法規による消費者の権利や当店の責任を制限しません。変更は将来の利用に適用し、成立済みの契約上の権利を遡って変更しません。お問い合わせ：${v.email}`:`Terms of service\n\n${identity}\n\nUse this website to browse products, place orders and obtain support. Provide accurate order information. Do not misuse the service, attack its systems or infringe others' rights. Review product descriptions, images and prices before purchasing. If a display error affects your order, we will contact you and resolve it in accordance with applicable law.\n\nPurchases are governed by the terms of sale; delivery by the shipping policy; returns by the refund policy; and personal data by the privacy policy. These terms do not waive mandatory consumer rights or liability that cannot lawfully be excluded. Changes apply prospectively and do not retroactively remove rights under existing orders. Contact: ${v.email}`;
 const legal=jp?`特定商取引法に基づく表記・事業者情報\n\n${identity}\n${v.manager?'運営責任者：'+v.manager:''}\n${v.registration?'登録・税務番号：'+v.registration:''}\n\n販売価格：商品ページに表示。\n商品代金以外の料金：${v.shippingFees}\n${duty}\n支払方法・時期：${v.payments}\n引渡時期：発送準備 ${v.processing}、配送 ${v.delivery}\n返品条件：受領後${v.returnDays}日以内にご連絡ください。任意返品は未使用の商品を対象とします。${returnCost} 不良品等の法定救済は別途適用されます。詳細は返品ポリシーに記載しています。\n返品先：${v.returnAddress}`:`Legal notice and seller disclosure\n\n${identity}\n${v.manager?'Responsible representative: '+v.manager:''}\n${v.registration?'Registration / tax identifier: '+v.registration:''}\n\nPrices are displayed on product pages. Additional charges: ${v.shippingFees}\n${duty}\nPayment methods and timing: ${v.payments}\nDelivery timing: processing ${v.processing}; transit ${v.delivery}\nReturn conditions: notify us within ${v.returnDays} days of receipt; voluntary returns cover unused items. ${returnCost} Statutory remedies for defective goods remain separate. See the returns policy for full details.\nReturn address: ${v.returnAddress}`;
 return Object.entries({SHIPPING_POLICY:shipping,REFUND_POLICY:refund,PRIVACY_POLICY:privacy,TERMS_OF_SERVICE:terms,TERMS_OF_SALE:sales,CONTACT_INFORMATION:identity,LEGAL_NOTICE:legal}).map(([type,text])=>({type,title:POLICY_TITLES[type],text:text.trim()}));
}
export function policyHtml(text){return text.split(/\n\s*\n/).map(p=>'<p>'+p.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])).replace(/\n/g,'<br>')+'</p>').join('\n');}
export function registerPolicies(app,getToken,apiCall=api){
 const drafts=new Map(),locks=new Set();
 const read=async(call)=>{const result=await call('query PolicySnapshot{shop{shopPolicies{type body}}}');if(!Array.isArray(result.shop?.shopPolicies))throw Error('Não foi possível ler as políticas atuais. Verifique read_legal_policies.');return result.shop.shopPolicies;};
 app.post('/api/policies/preview',async(req,res)=>{try{
  const dest=credentials(req.body.destination),policies=generatePolicies(req.body.settings);
  const token=await getToken(dest.shop,dest.clientId,dest.clientSecret),call=(q,v)=>apiCall(dest.shop,token,q,v),existing=await read(call);
  for(const [id,draft] of drafts)if(draft.expires<Date.now())drafts.delete(id);
  if(drafts.size>=100)throw Error('Há muitas prévias ativas. Aguarde alguns minutos.');
  const id=randomUUID();drafts.set(id,{accountId:req.account?.id,shop:dest.shop,clientId:dest.clientId,policies,existing,expires:Date.now()+30*60000});
  res.json({id,policies:policies.map(p=>({...p,existing:!!existing.find(e=>e.type===p.type)?.body?.trim()})),notice:'Modelo para produtos físicos e compras avulsas. Revise a operação real e as exigências dos países atendidos. Não garante conformidade jurídica em todos os países. Publica o texto base da loja, não traduções por Market.'});
 }catch(e){res.status(400).json({error:e.message});}});
 app.post('/api/policies/publish',async(req,res)=>{let shop;try{
  const dest=credentials(req.body.destination),draft=drafts.get(req.body.id);
  if(!draft||draft.accountId!==req.account?.id||draft.expires<Date.now()||draft.shop!==dest.shop||draft.clientId!==dest.clientId)throw Error('Prévia expirada ou destino alterado. Gere novamente.');
  if(req.body.confirmShop!==dest.shop)throw Error('Confirme o domínio da loja de destino.');
  const selected=req.body.policies;
  if(!Array.isArray(selected)||!selected.length||selected.length>7||new Set(selected.map(p=>p.type)).size!==selected.length||selected.some(p=>!draft.policies.some(d=>d.type===p.type)||typeof p.text!=='string'||!p.text.trim()||p.text.length>40000))throw Error('Seleção ou texto de política inválido.');
  if(locks.has(dest.shop))throw Error('Já existe uma publicação em andamento nesta loja.');
  shop=dest.shop;locks.add(shop);
  const token=await getToken(dest.shop,dest.clientId,dest.clientSecret),call=(q,v)=>apiCall(dest.shop,token,q,v),current=await read(call);
  if(selected.some(p=>(current.find(e=>e.type===p.type)?.body||'')!==(draft.existing.find(e=>e.type===p.type)?.body||'')))throw Error('As políticas mudaram desde a prévia. Gere novamente antes de substituir.');
  drafts.delete(req.body.id);
  const results=[];
  for(const p of selected){try{
   const data=checkPayload((await call('mutation PolicyPublish($shopPolicy:ShopPolicyInput!){shopPolicyUpdate(shopPolicy:$shopPolicy){shopPolicy{type body}userErrors{field message}}}',{shopPolicy:{type:p.type,body:policyHtml(p.text)}})).shopPolicyUpdate,'shopPolicyUpdate');
   if(data.shopPolicy?.type!==p.type||!data.shopPolicy.body?.trim())throw Error('Shopify não confirmou a gravação.');
   results.push({type:p.type,ok:true});
  }catch(e){results.push({type:p.type,ok:false,error:e.message});}}
  res.json({results});
 }catch(e){res.status(400).json({error:e.message});}finally{if(shop)locks.delete(shop);}});
}
